### ISSUE TITLE
Checkout existing telegram bot

### ISSUE THREAD

**Issue by sevazhidkov** [abdulhannanali/loklak-telegram-chat-bot#12]
HI! 
I created Tekegram bot for Loklak API: https://github.com/sevazhidkov/tweets-search-bot some time ago
It already announced in Fossasia Twitter. If you have improvements for it, you're welcome :)

**Comment by sudheesh001** [comment]
@sevazhidkov This GCI we're taking the effort of building the bots in different languages, this one is in Node.js so It should be good to go to continue. :+1:

**Comment by abdulhannanali** [comment]
Hi @sevazhidkov That's so awesome. I don't know python but your code seems really nicely written.

**Comment by sevazhidkov** [comment]
@sudheesh001 Sorry, didn't understand.
