### ISSUE TITLE
twitter emojis

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#13]
loklak api sends twitter emojis in html form

```
<img class="Emoji Emoji--forText" src="https://abs.twimg.com/emoji/v2/72x72/1f602.png" draggable="false" alt="😂" title="Gesicht mit Freudentränen" aria-label="Emoji: Gesicht mit Freudentränen">
```

but Telegram does not interpret html and it ruins the tweets with emojis. Use some thing such as cheerio or any thing else which only extracts the emojis. 
Sample tweet with emoji in telegram
![Sample tweet](http://i.imgur.com/xQG0Yyg.png)

**Comment by sudheesh001** [comment]
@abdulhannanali Looks like this will be of some help to you.

``` py
import telegram

L = telegram.Emoji()
listOfEmojis = dir(L)

EMOJISLIST = []
for i in listOfEmojis:
    EMOJISLIST.append(i)

for x in EMOJISLIST:
    print x
```

Or you can strip the `src` image, save it on the local system in the process in a /tmp/ location and serve it as an image from there.

Another option would be to parse the content for emoji content and replace with the corresponding Emoji from `telegram.Emoji()`

**Comment by abdulhannanali** [comment]
@sudheesh001 since telegram uses simple unicode emojis we won't need that code. 
 i just have to specify  the emojis in the text. Stripping the source tags will be a good option but telegram doesn't support inline images and sending them seperately will cause  even from the local dir can cause the images to appear in really big squares which will just make them out of context. Luckily the developers of loklak api were cool and kind enough to specify the unicode equivalent of the twitter image emoji in the `alt` attribute so I think I just have to get it using regular expression or a node jquery equivalent cheerio

**Comment by abdulhannanali** [comment]
@sudheesh001 This bug has been solved. This is the code I am using for displaying twitter emojis. Don't know if it's fast  enough.

```
  function emojiAssigner(text) {
    var $ = cheerio.load(`<div>${text}</div>`)
    $('div').children("img").each(function (idx, obj) {
      var alt = $(obj).attr("alt")
      $(obj).replaceWith(alt)
    })
    return $('div').text()
  }
```

**Comment by sudheesh001** [comment]
Looks good so far to me ! Very good work @abdulhannanali
