### ISSUE TITLE
multiple requests and loklak api

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#15]
since loklak api takes some time in order to respond so making a request each time we want to use the api is not scalable so we are going to store the statuses in the redis server and expire them automatically after a certain time. In this way we can reduce the latency.. Don't know if it's scalable since at the moment I am using redislabs free tier for  production.

**Comment by sudheesh001** [comment]
Good option ! We really need caching.

**Comment by abdulhannanali** [comment]
Yup! I am implementing a redis linked list for this purpose. Seems to be the best and the fastest option

**Comment by abdulhannanali** [comment]
This has been implemented. Thanks for your help @sudheesh001
