### ISSUE TITLE
make the user and search a two way process too

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#26]
as per mentor @sudheesh001 suggested let's make signup a 2 step process
![discussion with mentor](http://i.imgur.com/qefgPuR.png)

Like when a user enters a /user 
he gets to input only the username
Similarly, when a user enters /search he may only input the search term

**Comment by sudheesh001** [comment]
Exactly !

**Comment by abdulhannanali** [comment]
@sudheesh001 I have implemented it. Thanks for assuring.
