### ISSUE TITLE
implement a small express server which acts like loklak

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#30]
loklak has been down quite often in the yesterday and today slowing down my speed of development even further. I am thinking of developing an express server which acts as loklak and serve predefined results for the query. fastening up my development speed.

**Comment by sudheesh001** [comment]
loklak has moved to a backup server and the main one will be back online pretty soon.

**Comment by abdulhannanali** [comment]
yup! it's back in action with full speed. thanks
