### ISSUE TITLE
reconsidering the keyboard

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#31]
it just doesn't seem something right about the keyboard displayed. i might remove a few options from some keyboards and some in other and give them a refined look

**Comment by sudheesh001** [comment]
Great, Good work so far @abdulhannanali

**Comment by abdulhannanali** [comment]
@sudheesh001 thanks! I've got to learn a lot about software projects under your mentorship. thank you for your kind hel

**Comment by abdulhannanali** [comment]
@sudheesh001 sorry a typo. thank you for your kind *help. :+1:
