### ISSUE TITLE
add a basic search route but more enhancements needed

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#4]
A basic search route has been added but it's enough some enhancements to the search route are  needed such as browsing the tweets maintaining a session between them. Also mentor @Sudheesh001 mentions more apis for example
- GeoLocation API (for info based on the geo location)
- Crawler API (for crawling the api)
  WE also need to implement at least one of these

**Comment by sudheesh001** [comment]
Lets minimize the work needed to be only the search api or the user api for the minimal product, we can always introduce more people into contributing to this.

**Comment by abdulhannanali** [comment]
yes that's very better. i'll focus on implementing the minimal product with search and user api for now :+1:

**Comment by abdulhannanali** [comment]
@sudheesh001 thank you with your collaboration and mentorship, user and search api are now imlemented
