### ISSUE TITLE
Separate messages into files

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#5]
for the purpose of modularity separate some messages into separate files
such as lib/messages/startMessage.md etc

**Comment by abdulhannanali** [comment]
Yup this will make the lib/loklakTelegram.js look cleaner which it isn't yet

**Comment by sudheesh001** [comment]
I think this can be pushed out to later, the main aim is to build a working minimal prototype. We can focus on the rest later.

**Comment by abdulhannanali** [comment]
Yeah that's right..
