### ISSUE TITLE
Let the user browse the tweets 

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#6]
I am quite confused about this one on how should I go about maintaining session with the user. This can help us for browsing through the tweets and what to do about them. 
One solution can be using the node redis.

**Comment by abdulhannanali** [comment]
We are not going to use in memory storage and ruin our app due to memory leaks. So node redis seems a good option. I'll refer my awesome mentor @sudheesh001 on this one

**Comment by sudheesh001** [comment]
I do not know if there's a definite way of maintaining a session, telegram bots run on queries, We can maintain the sessions of the users based on the names into an in memory database like that of Redis, or maybe we could use MongoDB to store the data as JSON. What do you think ?

**Comment by abdulhannanali** [comment]
Yup! We can go with MongoDB but it'll give our real time app some overhead. Since our app needs to perform fast and nothing beats redis in the performance. Also, some chat services such as gitter.im already use redis.io so I think redis might be the way to go.

**Comment by sudheesh001** [comment]
As I mentioned

> , in memory databases like that of redis.

Lets go for redis :smile:

**Comment by abdulhannanali** [comment]
Yes sir! Let's go for redis..

**Comment by abdulhannanali** [comment]
:+1:

**Comment by abdulhannanali** [comment]
I have now started to work on it. Let's see how it goes. Excited to use Node Redis

**Comment by abdulhannanali** [comment]
This is good to ship
